- name: Run Db2 utility
  hosts: all
  gather_facts: false
  tasks:
    - name: Authenticate with UMS
      ansible.builtin.include_role:
        name: ums_login

    - name: Run Db2 utility
      ansible.builtin.include_role:
        name: daj_util
      vars:
        daj_util_ssid: DSN
        daj_util_sysname: lpar
        daj_util_utilityname: COPY
        daj_util_object_type: TS
        daj_util_database: DSN8D13A
        daj_util_object_name: DSN8S13E
        daj_util_objects: [
          {
            "objectType": "{{ daj_util_object_type }}",
            "databaseName": "{{ daj_util_database_name }}",
            "objectName": "{{ daj_util_object_name }} "
          }
        ]
        daj_util_verbose: false
    - name: delete dataset
      ansible.builtin.file:
        path: "/u/{{ ansible_user | lower }}/DAJ1.OUTPUT"
        state: absent

    - name: create dataset
      ansible.builtin.file:
        path: "/u/{{ ansible_user | lower }}/DAJ1.OUTPUT"
        state: touch

    - name: write summary to dataset
      ibm.ibm_zos_core.zos_lineinfile:
        src: "/u/{{ ansible_user | lower }}/DAJ1.OUTPUT"
        line: Utility {{ item.action }} on object {{ item.targetQualifier}}.{{ item.targetObject }} has status {{ item.status }} with return code {{ item.returnCode }} (utility id A{{ item.actionIdentifier }})
      loop: "{{ daj_util_output.results | map(attribute='json') | map(attribute='actionList') | flatten(1) | map(attribute='actions') |flatten(1) }}"
      loop_control:
       label: "{{ item.targetObject }}"

